from __future__ import annotations

import json
import logging
from collections.abc import Iterable
from contextlib import contextmanager
from datetime import datetime

try:
    from datetime import UTC
except ImportError:
    from datetime import timedelta, timezone

    UTC = timezone(timedelta(0))
from typing import Any

from src.config import settings
from src.services.auth import hash_password

logger = logging.getLogger(__name__)


def initialize_database() -> None:
    with get_connection() as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS app_accounts (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                email TEXT NOT NULL UNIQUE,
                full_name TEXT NOT NULL,
                role TEXT NOT NULL CHECK (role IN ('admin', 'analyst')),
                password_hash TEXT NOT NULL,
                is_active BOOLEAN NOT NULL DEFAULT TRUE,
                created_at TEXT NOT NULL
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS users (
                id TEXT PRIMARY KEY,
                username TEXT NOT NULL UNIQUE,
                full_name TEXT NOT NULL,
                email TEXT,
                department TEXT,
                job_role TEXT,
                status TEXT NOT NULL DEFAULT 'active',
                risk_score INTEGER NOT NULL DEFAULT 0,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS devices (
                id TEXT PRIMARY KEY,
                hostname TEXT NOT NULL,
                os TEXT,
                ip_address TEXT,
                assigned_user_id TEXT REFERENCES users(id),
                status TEXT NOT NULL DEFAULT 'offline',
                risk_score INTEGER NOT NULL DEFAULT 0,
                last_seen TEXT,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS event_logs (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                source_id TEXT NOT NULL UNIQUE,
                source_file TEXT NOT NULL,
                timestamp TEXT NOT NULL,
                user_id TEXT REFERENCES users(id),
                device_id TEXT REFERENCES devices(id),
                event_type TEXT NOT NULL,
                action TEXT,
                resource TEXT,
                metadata_json TEXT NOT NULL DEFAULT '{}',
                raw_json TEXT NOT NULL DEFAULT '{}',
                created_at TEXT NOT NULL
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS feature_windows (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id TEXT NOT NULL REFERENCES users(id),
                device_id TEXT REFERENCES devices(id),
                window_start TEXT NOT NULL,
                window_end TEXT NOT NULL,
                feature_summary_json TEXT NOT NULL DEFAULT '{}',
                baseline_context_json TEXT NOT NULL DEFAULT '{}',
                created_at TEXT NOT NULL
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS model_artifacts (
                model_version TEXT PRIMARY KEY,
                artifact_path TEXT NOT NULL,
                training_config_json TEXT NOT NULL DEFAULT '{}',
                metrics_json TEXT NOT NULL DEFAULT '{}',
                created_at TEXT NOT NULL
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS alerts (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id TEXT REFERENCES users(id),
                device_id TEXT REFERENCES devices(id),
                event_log_id INTEGER REFERENCES event_logs(id),
                model_version TEXT REFERENCES model_artifacts(model_version),
                title TEXT NOT NULL,
                severity TEXT NOT NULL CHECK (severity IN ('low', 'medium', 'high', 'critical')),
                status TEXT NOT NULL DEFAULT 'new'
                    CHECK (status IN ('new', 'investigating', 'resolved', 'false_positive')),
                risk_score INTEGER NOT NULL,
                anomaly_score DOUBLE PRECISION,
                risk_factors_json TEXT NOT NULL DEFAULT '[]',
                explanation TEXT,
                detected_at TEXT NOT NULL,
                updated_at TEXT NOT NULL
            )
            """
        )
        conn.execute("CREATE INDEX IF NOT EXISTS idx_event_logs_timestamp ON event_logs(timestamp)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_event_logs_user ON event_logs(user_id)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_event_logs_device ON event_logs(device_id)")
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS raw_user_logs (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                source_id TEXT NOT NULL UNIQUE,
                collector_type TEXT NOT NULL,
                event_type TEXT NOT NULL
                    CHECK (event_type IN (
                        'logon', 'device', 'file', 'http', 'email',
                        'process', 'network', 'ldap', 'psychometric', 'custom'
                    )),
                timestamp TEXT NOT NULL,
                user_id TEXT,
                device_id TEXT,
                raw_payload_json TEXT NOT NULL,
                ingest_metadata_json TEXT NOT NULL DEFAULT '{}',
                normalized_event_id INTEGER REFERENCES event_logs(id),
                created_at TEXT NOT NULL
            )
            """
        )
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_raw_user_logs_timestamp ON raw_user_logs(timestamp)"
        )
        conn.execute("CREATE INDEX IF NOT EXISTS idx_raw_user_logs_user ON raw_user_logs(user_id)")
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_raw_user_logs_device ON raw_user_logs(device_id)"
        )
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_raw_user_logs_event_type ON raw_user_logs(event_type)"
        )
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_raw_user_logs_collector_type ON raw_user_logs(collector_type)"
        )
        _ensure_raw_user_logs_event_type_check(conn)
        conn.execute("CREATE INDEX IF NOT EXISTS idx_alerts_status ON alerts(status)")
        conn.execute("CREATE INDEX IF NOT EXISTS idx_alerts_severity ON alerts(severity)")
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_devices_assigned_user ON devices(assigned_user_id)"
        )
        conn.execute("CREATE INDEX IF NOT EXISTS idx_alerts_user_status ON alerts(user_id, status)")
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_alerts_device_status ON alerts(device_id, status)"
        )
        _seed_accounts(conn)
        _seed_model_artifacts(conn)
        # _seed_domain_data(conn)  # Removed mock data so only CSV data shows


@contextmanager
def get_connection() -> Iterable[Any]:
    try:
        import psycopg
        from psycopg.rows import dict_row
    except ImportError as exc:
        raise RuntimeError(
            "PostgreSQL driver missing. Install dependencies with `pip install -r requirements.txt`."
        ) from exc

    conn = psycopg.connect(settings.database_url, row_factory=dict_row)
    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def get_account_by_email(email: str) -> dict[str, Any] | None:
    with get_connection() as conn:
        row = conn.execute(
            "SELECT * FROM app_accounts WHERE lower(email) = lower(%s)", (email,)
        ).fetchone()
        return _row_to_dict(row)


def get_account_by_id(account_id: int) -> dict[str, Any] | None:
    with get_connection() as conn:
        row = conn.execute("SELECT * FROM app_accounts WHERE id = %s", (account_id,)).fetchone()
        return _row_to_dict(row)


def list_users(filters: dict[str, Any]) -> list[dict[str, Any]]:
    where, params = _user_filters(filters)
    return _fetch_all(
        "SELECT * FROM users", where, params, "risk_score DESC, username ASC", filters
    )


def count_users(filters: dict[str, Any]) -> int:
    where, params = _user_filters(filters)
    return _count("users", where, params)


def get_user(user_id: str) -> dict[str, Any] | None:
    with get_connection() as conn:
        return _row_to_dict(
            conn.execute("SELECT * FROM users WHERE id = %s", (user_id,)).fetchone()
        )


def create_user(payload: dict[str, Any]) -> dict[str, Any]:
    now = utc_now()
    user_id = payload["id"]
    with get_connection() as conn:
        conn.execute(
            """
            INSERT INTO users (id, username, full_name, email, department, job_role, status, risk_score, created_at, updated_at)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            """,
            (
                user_id,
                payload["username"],
                payload["full_name"],
                payload.get("email"),
                payload.get("department"),
                payload.get("job_role"),
                payload.get("status", "active"),
                payload.get("risk_score", 0),
                now,
                now,
            ),
        )
    return get_user(user_id) or {}


def update_user(user_id: str, payload: dict[str, Any]) -> dict[str, Any] | None:
    return _update_by_id(
        "users",
        user_id,
        payload,
        allowed={"email", "department", "job_role", "status", "risk_score"},
    )


def list_devices(filters: dict[str, Any]) -> list[dict[str, Any]]:
    where, params = _device_filters(filters)
    return _fetch_all(
        """
        SELECT d.*, u.username AS assigned_username, u.full_name AS assigned_user_name
        FROM devices d
        LEFT JOIN users u ON u.id = d.assigned_user_id
        """,
        where,
        params,
        "d.risk_score DESC, d.hostname ASC",
        filters,
    )


def count_devices(filters: dict[str, Any]) -> int:
    where, params = _device_filters(filters)
    return _count("devices d", where, params)


def get_device(device_id: str) -> dict[str, Any] | None:
    with get_connection() as conn:
        row = conn.execute(
            """
            SELECT d.*, u.username AS assigned_username, u.full_name AS assigned_user_name
            FROM devices d
            LEFT JOIN users u ON u.id = d.assigned_user_id
            WHERE d.id = %s
            """,
            (device_id,),
        ).fetchone()
        return _row_to_dict(row)


def create_device(payload: dict[str, Any]) -> dict[str, Any]:
    now = utc_now()
    device_id = payload["id"]
    with get_connection() as conn:
        conn.execute(
            """
            INSERT INTO devices (id, hostname, os, ip_address, assigned_user_id, status, risk_score, last_seen, created_at, updated_at)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            """,
            (
                device_id,
                payload["hostname"],
                payload.get("os"),
                payload.get("ip_address"),
                payload.get("assigned_user_id"),
                payload.get("status", "offline"),
                payload.get("risk_score", 0),
                payload.get("last_seen"),
                now,
                now,
            ),
        )
    return get_device(device_id) or {}


def update_device(device_id: str, payload: dict[str, Any]) -> dict[str, Any] | None:
    return _update_by_id(
        "devices",
        device_id,
        payload,
        allowed={
            "hostname",
            "os",
            "ip_address",
            "assigned_user_id",
            "status",
            "risk_score",
            "last_seen",
        },
    )


def ingest_event(payload: dict[str, Any]) -> dict[str, Any]:
    now = utc_now()
    metadata_json = json.dumps(payload.get("metadata") or {}, sort_keys=True)
    raw_json = json.dumps(payload.get("raw") or {}, sort_keys=True)
    with get_connection() as conn:
        row = conn.execute(
            """
            INSERT INTO event_logs (
                source_id, source_file, timestamp, user_id, device_id, event_type,
                action, resource, metadata_json, raw_json, created_at
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT(source_id) DO UPDATE SET
                source_file = excluded.source_file,
                timestamp = excluded.timestamp,
                user_id = excluded.user_id,
                device_id = excluded.device_id,
                event_type = excluded.event_type,
                action = excluded.action,
                resource = excluded.resource,
                metadata_json = excluded.metadata_json,
                raw_json = excluded.raw_json
            RETURNING *
            """,
            (
                payload["source_id"],
                payload["source_file"],
                payload["timestamp"],
                payload.get("user_id"),
                payload.get("device_id"),
                payload["event_type"],
                payload.get("action"),
                payload.get("resource"),
                metadata_json,
                raw_json,
                now,
            ),
        ).fetchone()
        return _decode_json_fields(_row_to_dict(row) or {})


def list_events(filters: dict[str, Any]) -> list[dict[str, Any]]:
    where, params = _event_filters(filters)
    rows = _fetch_all("SELECT * FROM event_logs", where, params, "timestamp DESC, id DESC", filters)
    return [_decode_json_fields(row) for row in rows]


def count_events(filters: dict[str, Any]) -> int:
    where, params = _event_filters(filters)
    return _count("event_logs", where, params)


def ingest_raw_log(payload: dict[str, Any]) -> dict[str, Any]:
    now = utc_now()
    raw_payload_json = json.dumps(payload.get("raw_payload") or {}, sort_keys=True)
    ingest_metadata_json = json.dumps(payload.get("ingest_metadata") or {}, sort_keys=True)
    with get_connection() as conn:
        row = conn.execute(
            """
            INSERT INTO raw_user_logs (
                source_id, collector_type, event_type, timestamp,
                user_id, device_id, raw_payload_json, ingest_metadata_json, created_at
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT(source_id) DO UPDATE SET
                collector_type = excluded.collector_type,
                event_type = excluded.event_type,
                timestamp = excluded.timestamp,
                user_id = excluded.user_id,
                device_id = excluded.device_id,
                raw_payload_json = excluded.raw_payload_json,
                ingest_metadata_json = excluded.ingest_metadata_json
            RETURNING *
            """,
            (
                payload["source_id"],
                payload["collector_type"],
                payload["event_type"],
                payload["timestamp"],
                payload.get("user_id"),
                payload.get("device_id"),
                raw_payload_json,
                ingest_metadata_json,
                now,
            ),
        ).fetchone()
        return _decode_raw_log_fields(_row_to_dict(row) or {})


def batch_ingest_raw_logs(records: list[dict[str, Any]]) -> dict[str, Any]:
    created_or_updated = 0
    failed = 0
    errors: list[dict[str, Any]] = []
    now = utc_now()
    with get_connection() as conn:
        for idx, record in enumerate(records):
            conn.execute("SAVEPOINT sp_raw_batch")
            try:
                raw_payload_json = json.dumps(record.get("raw_payload") or {}, sort_keys=True)
                ingest_metadata_json = json.dumps(
                    record.get("ingest_metadata") or {}, sort_keys=True
                )
                conn.execute(
                    """
                    INSERT INTO raw_user_logs (
                        source_id, collector_type, event_type, timestamp,
                        user_id, device_id, raw_payload_json, ingest_metadata_json, created_at
                    )
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
                    ON CONFLICT(source_id) DO UPDATE SET
                        collector_type = excluded.collector_type,
                        event_type = excluded.event_type,
                        timestamp = excluded.timestamp,
                        user_id = excluded.user_id,
                        device_id = excluded.device_id,
                        raw_payload_json = excluded.raw_payload_json,
                        ingest_metadata_json = excluded.ingest_metadata_json
                    """,
                    (
                        record["source_id"],
                        record["collector_type"],
                        record["event_type"],
                        record["timestamp"],
                        record.get("user_id"),
                        record.get("device_id"),
                        raw_payload_json,
                        ingest_metadata_json,
                        now,
                    ),
                )
                conn.execute("RELEASE SAVEPOINT sp_raw_batch")
                created_or_updated += 1
            except Exception:
                logger.exception("Failed to ingest raw log at index %d", idx)
                conn.execute("ROLLBACK TO SAVEPOINT sp_raw_batch")
                conn.execute("RELEASE SAVEPOINT sp_raw_batch")
                failed += 1
                errors.append({"index": idx, "error": "failed_to_ingest_record"})
    return {"created_or_updated": created_or_updated, "failed": failed, "errors": errors}


def get_raw_log(log_id: int) -> dict[str, Any] | None:
    with get_connection() as conn:
        row = conn.execute("SELECT * FROM raw_user_logs WHERE id = %s", (log_id,)).fetchone()
        return _decode_raw_log_fields(_row_to_dict(row) or {}) if row else None


def list_raw_logs(filters: dict[str, Any]) -> list[dict[str, Any]]:
    where, params = _raw_log_filters(filters)
    rows = _fetch_all(
        "SELECT * FROM raw_user_logs", where, params, "timestamp DESC, id DESC", filters
    )
    return [_decode_raw_log_fields(row) for row in rows]


def count_raw_logs(filters: dict[str, Any]) -> int:
    where, params = _raw_log_filters(filters)
    return _count("raw_user_logs", where, params)


def _raw_log_filters(filters: dict[str, Any]) -> tuple[list[str], list[Any]]:
    return _build_filters(
        filters,
        {
            "user_id": "user_id",
            "device_id": "device_id",
            "event_type": "event_type",
            "collector_type": "collector_type",
        },
    )


# ---------------------------------------------------------------------------
# Frontend-compatible query helpers
# ---------------------------------------------------------------------------


def get_dashboard_summary() -> dict[str, Any]:
    with get_connection() as conn:
        total_users = int(conn.execute("SELECT COUNT(*) AS c FROM users").fetchone()["c"])
        total_devices = int(conn.execute("SELECT COUNT(*) AS c FROM devices").fetchone()["c"])
        total_logs = int(conn.execute("SELECT COUNT(*) AS c FROM event_logs").fetchone()["c"])

        open_alerts = int(
            conn.execute(
                "SELECT COUNT(*) AS c FROM alerts WHERE status NOT IN ('resolved', 'false_positive')"
            ).fetchone()["c"]
        )
        high_critical_alerts = int(
            conn.execute(
                "SELECT COUNT(*) AS c FROM alerts "
                "WHERE status NOT IN ('resolved', 'false_positive') AND severity IN ('high', 'critical')"
            ).fetchone()["c"]
        )
        avg_row = conn.execute("SELECT COALESCE(AVG(risk_score), 0) AS avg FROM users").fetchone()
        average_risk_score = round(float(avg_row["avg"]), 1)

        model_row = conn.execute(
            "SELECT model_version FROM model_artifacts ORDER BY created_at DESC LIMIT 1"
        ).fetchone()
        current_model_version = model_row["model_version"] if model_row else None

        last_import_row = conn.execute(
            "SELECT MAX(ts) AS ts FROM ("
            "  SELECT MAX(timestamp) AS ts FROM event_logs"
            "  UNION ALL"
            "  SELECT MAX(timestamp) AS ts FROM raw_user_logs"
            ") sub"
        ).fetchone()
        last_import_time = (
            last_import_row["ts"] if last_import_row and last_import_row["ts"] else None
        )

    return {
        "totalUsers": total_users,
        "totalDevices": total_devices,
        "totalLogs": total_logs,
        "openAlerts": open_alerts,
        "highCriticalAlerts": high_critical_alerts,
        "averageRiskScore": average_risk_score,
        "currentModelVersion": current_model_version,
        "lastImportTime": last_import_time,
    }


def list_frontend_users(limit: int = 200) -> list[dict[str, Any]]:
    sql = """
        SELECT
            u.id,
            u.username AS account,
            u.full_name AS name,
            u.department,
            u.job_role AS role,
            u.status,
            u.risk_score AS "riskScore",
            COALESCE(dev.assigned_devices, 0) AS "assignedDevices",
            COALESCE(alo.open_alerts, 0) AS "openAlerts",
            ls.last_seen AS "lastSeen"
        FROM users u
        LEFT JOIN LATERAL (
            SELECT COUNT(*) AS assigned_devices FROM devices d WHERE d.assigned_user_id = u.id
        ) dev ON TRUE
        LEFT JOIN LATERAL (
            SELECT COUNT(*) AS open_alerts FROM alerts a
            WHERE a.user_id = u.id AND a.status NOT IN ('resolved', 'false_positive')
        ) alo ON TRUE
        LEFT JOIN LATERAL (
            SELECT MAX(d2.last_seen) AS last_seen FROM devices d2 WHERE d2.assigned_user_id = u.id
        ) ls ON TRUE
        ORDER BY u.risk_score DESC, u.username ASC
        LIMIT %s
    """
    with get_connection() as conn:
        return [_row_to_dict(row) or {} for row in conn.execute(sql, (limit,)).fetchall()]


def list_frontend_devices(limit: int = 200) -> list[dict[str, Any]]:
    sql = """
        SELECT
            d.id,
            d.hostname,
            u.username AS "assignedUser",
            u.department,
            CASE WHEN d.status = 'online' THEN 'active' ELSE 'inactive' END AS status,
            d.risk_score AS "riskScore",
            COALESCE(alo.open_alerts, 0) AS "openAlerts",
            d.last_seen AS "lastSeen"
        FROM devices d
        LEFT JOIN users u ON u.id = d.assigned_user_id
        LEFT JOIN LATERAL (
            SELECT COUNT(*) AS open_alerts FROM alerts a
            WHERE a.device_id = d.id AND a.status NOT IN ('resolved', 'false_positive')
        ) alo ON TRUE
        ORDER BY d.risk_score DESC, d.hostname ASC
        LIMIT %s
    """
    with get_connection() as conn:
        return [_row_to_dict(row) or {} for row in conn.execute(sql, (limit,)).fetchall()]


def list_frontend_logs(limit: int = 100) -> list[dict[str, Any]]:
    sql = """
        SELECT
            id::TEXT AS id,
            timestamp,
            event_type AS "eventType",
            user_id AS "userId",
            device_id AS "deviceId",
            COALESCE(action, 'UNKNOWN') AS action,
            source_file AS "sourceFile",
            source_id AS "sourceId",
            COALESCE(resource, '') AS "rawDetail"
        FROM event_logs
        ORDER BY timestamp DESC, id DESC
        LIMIT %s
    """
    with get_connection() as conn:
        return [_row_to_dict(row) or {} for row in conn.execute(sql, (limit,)).fetchall()]


# ---------------------------------------------------------------------------
# Alert CRUD
# ---------------------------------------------------------------------------


def create_alert(payload: dict[str, Any]) -> dict[str, Any]:
    now = utc_now()
    with get_connection() as conn:
        row = conn.execute(
            """
            INSERT INTO alerts (
                user_id, device_id, event_log_id, model_version, title,
                severity, status, risk_score, anomaly_score, risk_factors_json,
                explanation, detected_at, updated_at
            ) VALUES (%s, %s, %s, %s, %s, %s, 'new', %s, %s, %s, %s, %s, %s)
            RETURNING *
            """,
            (
                payload.get("user_id"),
                payload.get("device_id"),
                payload.get("event_log_id"),
                payload.get("model_version"),
                payload["title"],
                payload["severity"],
                payload["risk_score"],
                payload.get("anomaly_score"),
                json.dumps(payload.get("risk_factors", [])),
                payload.get("explanation"),
                now,
                now,
            ),
        ).fetchone()
        return _decode_alert_fields(_row_to_dict(row) or {})


def get_alert(alert_id: int) -> dict[str, Any] | None:
    with get_connection() as conn:
        row = conn.execute("SELECT * FROM alerts WHERE id = %s", (alert_id,)).fetchone()
        if row:
            return _decode_alert_fields(_row_to_dict(row))
        return None


def update_alert_status(alert_id: int, status: str) -> dict[str, Any] | None:
    now = utc_now()
    with get_connection() as conn:
        row = conn.execute(
            """
            UPDATE alerts SET status = %s, updated_at = %s
            WHERE id = %s RETURNING *
            """,
            (status, now, alert_id),
        ).fetchone()
        if row:
            return _decode_alert_fields(_row_to_dict(row))
        return None


def list_alerts(
    filters: dict[str, Any] | None = None,
    limit: int = 100,
    offset: int = 0,
) -> list[dict[str, Any]]:
    where, params = _alert_filters(filters or {})
    sql = "SELECT * FROM alerts"
    if where:
        sql += " WHERE " + " AND ".join(where)
    sql += " ORDER BY detected_at DESC, id DESC LIMIT %s OFFSET %s"
    params.extend([limit, offset])
    with get_connection() as conn:
        return [_decode_alert_fields(_row_to_dict(row) or {}) for row in conn.execute(sql, params).fetchall()]


def count_alerts(filters: dict[str, Any] | None = None) -> int:
    where, params = _alert_filters(filters or {})
    sql = "SELECT COUNT(*) FROM alerts"
    if where:
        sql += " WHERE " + " AND ".join(where)
    with get_connection() as conn:
        return conn.execute(sql, params).fetchone()[0]


def list_frontend_alerts(limit: int = 100) -> list[dict[str, Any]]:
    sql = """
        SELECT
            id,
            user_id AS "userId",
            device_id AS "deviceId",
            title,
            severity,
            status,
            risk_score AS "riskScore",
            anomaly_score AS "anomalyScore",
            explanation,
            detected_at AS "detectedAt",
            updated_at AS "updatedAt"
        FROM alerts
        ORDER BY detected_at DESC, id DESC
        LIMIT %s
    """
    with get_connection() as conn:
        return [_row_to_dict(row) or {} for row in conn.execute(sql, (limit,)).fetchall()]


def get_alert_summary() -> dict[str, Any]:
    with get_connection() as conn:
        row = conn.execute("""
            SELECT
                COUNT(*) AS total,
                COUNT(*) FILTER (WHERE status = 'new') AS open_count,
                COUNT(*) FILTER (WHERE severity IN ('high', 'critical') AND status = 'new') AS high_critical_open
            FROM alerts
        """).fetchone()
        return _row_to_dict(row) or {}


def get_alerts_over_time(days: int = 30) -> list[dict[str, Any]]:
    with get_connection() as conn:
        rows = conn.execute("""
            SELECT
                DATE(detected_at) AS date,
                severity,
                COUNT(*) AS count
            FROM alerts
            WHERE detected_at >= NOW() - INTERVAL '%s days'
            GROUP BY DATE(detected_at), severity
            ORDER BY date DESC
        """, (days,)).fetchall()
        return [_row_to_dict(row) or {} for row in rows]


def get_severity_distribution() -> list[dict[str, Any]]:
    with get_connection() as conn:
        rows = conn.execute("""
            SELECT severity, COUNT(*) AS count
            FROM alerts
            GROUP BY severity
            ORDER BY CASE severity
                WHEN 'critical' THEN 1
                WHEN 'high' THEN 2
                WHEN 'medium' THEN 3
                WHEN 'low' THEN 4
            END
        """).fetchall()
        return [_row_to_dict(row) or {} for row in rows]


def get_top_risk_users(limit: int = 10) -> list[dict[str, Any]]:
    with get_connection() as conn:
        rows = conn.execute("""
            SELECT
                u.id,
                u.username,
                u.full_name AS name,
                u.department,
                u.risk_score AS "riskScore",
                COUNT(a.id) AS alert_count
            FROM users u
            LEFT JOIN alerts a ON a.user_id = u.id AND a.status = 'new'
            GROUP BY u.id, u.username, u.full_name, u.department, u.risk_score
            ORDER BY u.risk_score DESC
            LIMIT %s
        """, (limit,)).fetchall()
        return [_row_to_dict(row) or {} for row in rows]


def get_top_risk_devices(limit: int = 10) -> list[dict[str, Any]]:
    with get_connection() as conn:
        rows = conn.execute("""
            SELECT
                d.id,
                d.hostname,
                d.assigned_user_id AS "assignedUser",
                d.risk_score AS "riskScore",
                COUNT(a.id) AS alert_count
            FROM devices d
            LEFT JOIN alerts a ON a.device_id = d.id AND a.status = 'new'
            GROUP BY d.id, d.hostname, d.assigned_user_id, d.risk_score
            ORDER BY d.risk_score DESC
            LIMIT %s
        """, (limit,)).fetchall()
        return [_row_to_dict(row) or {} for row in rows]


def _alert_filters(filters: dict[str, Any]) -> tuple[list[str], list[Any]]:
    where: list[str] = []
    params: list[Any] = []
    if filters.get("status"):
        where.append("status = %s")
        params.append(filters["status"])
    if filters.get("severity"):
        where.append("severity = %s")
        params.append(filters["severity"])
    if filters.get("user_id"):
        where.append("user_id = %s")
        params.append(filters["user_id"])
    if filters.get("device_id"):
        where.append("device_id = %s")
        params.append(filters["device_id"])
    return where, params


def _decode_alert_fields(row: dict[str, Any]) -> dict[str, Any]:
    if "risk_factors_json" in row:
        row["risk_factors"] = json.loads(row.pop("risk_factors_json") or "[]")
    return row


def _decode_raw_log_fields(row: dict[str, Any]) -> dict[str, Any]:
    for key in ("raw_payload_json", "ingest_metadata_json"):
        if key in row:
            decoded_key = key.removesuffix("_json")
            row[decoded_key] = json.loads(row.pop(key) or "{}")
    return row

def create_alert(payload: dict[str, Any]) -> dict[str, Any]:
    now = utc_now()
    risk_factors_json = json.dumps(payload.get("risk_factors") or [])
    with get_connection() as conn:
        row = conn.execute(
            """
            INSERT INTO alerts (
                user_id, device_id, event_log_id, model_version, title, severity, status,
                risk_score, anomaly_score, risk_factors_json, explanation, detected_at, updated_at
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            RETURNING *
            """,
            (
                payload.get("user_id"),
                payload.get("device_id"),
                payload.get("event_log_id"),
                payload.get("model_version"),
                payload["title"],
                payload.get("severity", "medium"),
                payload.get("status", "new"),
                payload["risk_score"],
                payload.get("anomaly_score"),
                risk_factors_json,
                payload.get("explanation"),
                now,
                now,
            )
        ).fetchone()
        return _row_to_dict(row) or {}

def list_frontend_alerts(limit: int = 100) -> list[dict[str, Any]]:
    sql = """
        SELECT
            a.id::TEXT AS id,
            a.title,
            a.severity,
            a.status,
            a.risk_score AS "riskScore",
            a.anomaly_score AS "anomalyScore",
            a.risk_factors_json AS "riskFactorsJson",
            a.explanation,
            a.detected_at AS "detectedAt",
            u.username AS "userName",
            d.hostname AS "deviceName"
        FROM alerts a
        LEFT JOIN users u ON u.id = a.user_id
        LEFT JOIN devices d ON d.id = a.device_id
        ORDER BY a.risk_score DESC, a.detected_at DESC
        LIMIT %s
    """
    with get_connection() as conn:
        rows = conn.execute(sql, (limit,)).fetchall()
        result = []
        for row in rows:
            r = _row_to_dict(row) or {}
            r["riskFactors"] = json.loads(r.pop("riskFactorsJson") or "[]")
            result.append(r)
        return result


_RAW_LOG_EVENT_TYPES = (
    "logon",
    "device",
    "file",
    "http",
    "email",
    "process",
    "network",
    "ldap",
    "psychometric",
    "custom",
)


def _ensure_raw_user_logs_event_type_check(conn: Any) -> None:
    constraint_name = "raw_user_logs_event_type_check"
    row = conn.execute(
        """
        SELECT 1
        FROM pg_constraint c
        JOIN pg_class r ON r.oid = c.conrelid
        JOIN pg_namespace n ON n.oid = r.relnamespace
        WHERE r.relname = 'raw_user_logs'
          AND c.conname = %s
          AND c.contype = 'c'
        """,
        (constraint_name,),
    ).fetchone()
    if row is None:
        values = ", ".join(f"'{v}'" for v in _RAW_LOG_EVENT_TYPES)
        placeholders = ", ".join(["%s"] * len(_RAW_LOG_EVENT_TYPES))
        conn.execute(
            f"UPDATE raw_user_logs SET event_type = 'custom' WHERE event_type NOT IN ({placeholders})",
            list(_RAW_LOG_EVENT_TYPES),
        )
        conn.execute(
            f"ALTER TABLE raw_user_logs ADD CONSTRAINT {constraint_name} CHECK (event_type IN ({values}))"
        )


def utc_now() -> str:
    return datetime.now(UTC).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def _seed_accounts(conn: Any) -> None:
    now = utc_now()
    accounts = [
        ("admin@demo.com", "Demo Admin", "admin", "admin123"),
        ("analyst@demo.com", "Demo Analyst", "analyst", "analyst123"),
    ]
    for email, full_name, role, password in accounts:
        conn.execute(
            """
            INSERT INTO app_accounts (email, full_name, role, password_hash, is_active, created_at)
            VALUES (%s, %s, %s, %s, TRUE, %s)
            ON CONFLICT(email) DO NOTHING
            """,
            (email, full_name, role, hash_password(password), now),
        )


def _seed_model_artifacts(conn: Any) -> None:
    now = utc_now()
    training_config = {
        "source": "pretrained_artifact",
        "algorithm": "OneClassSVM",
        "artifact": settings.ocsvm_model_path,
        "training": "not_run_by_backend",
    }
    metrics = {
        "nu": 0.005,
        "kernel": "rbf",
        "gamma": "scale",
        "max_benign_train": 30000,
    }
    conn.execute(
        """
        INSERT INTO model_artifacts (model_version, artifact_path, training_config_json, metrics_json, created_at)
        VALUES (%s, %s, %s, %s, %s)
        ON CONFLICT(model_version) DO UPDATE SET
            artifact_path = excluded.artifact_path,
            training_config_json = excluded.training_config_json,
            metrics_json = excluded.metrics_json
        """,
        (
            settings.ocsvm_model_version,
            settings.ocsvm_model_path,
            json.dumps(training_config, sort_keys=True),
            json.dumps(metrics, sort_keys=True),
            now,
        ),
    )


def _seed_domain_data(conn: Any) -> None:
    now = utc_now()
    users = [
        (
            "ACM0001",
            "acm0001",
            "Alice M. Carter",
            "alice.carter@example.com",
            "Finance",
            "Accountant",
            "active",
            18,
        ),
        (
            "BTR0002",
            "btr0002",
            "Bao Tran",
            "bao.tran@example.com",
            "Engineering",
            "Developer",
            "active",
            42,
        ),
        (
            "CNL0003",
            "cnl0003",
            "Chi Nguyen",
            "chi.nguyen@example.com",
            "HR",
            "HR Specialist",
            "active",
            7,
        ),
    ]
    for row in users:
        conn.execute(
            """
            INSERT INTO users
            (id, username, full_name, email, department, job_role, status, risk_score, created_at, updated_at)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT(id) DO NOTHING
            """,
            (*row, now, now),
        )

    devices = [
        (
            "PC-1001",
            "FIN-WS-1001",
            "Windows 11",
            "10.10.1.21",
            "ACM0001",
            "online",
            12,
            "2026-06-13T08:12:00Z",
        ),
        (
            "PC-2002",
            "ENG-LT-2002",
            "Ubuntu 24.04",
            "10.10.2.44",
            "BTR0002",
            "online",
            39,
            "2026-06-13T08:09:00Z",
        ),
        (
            "PC-3003",
            "HR-WS-3003",
            "Windows 10",
            "10.10.3.18",
            "CNL0003",
            "offline",
            4,
            "2026-06-12T17:42:00Z",
        ),
    ]
    for row in devices:
        conn.execute(
            """
            INSERT INTO devices
            (id, hostname, os, ip_address, assigned_user_id, status, risk_score, last_seen, created_at, updated_at)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT(id) DO NOTHING
            """,
            (*row, now, now),
        )


def _build_filters(filters: dict[str, Any], columns: dict[str, str]) -> tuple[list[str], list[Any]]:
    where: list[str] = []
    params: list[Any] = []
    for key, column in columns.items():
        value = filters.get(key)
        if value is not None:
            where.append(f"{column} = %s")
            params.append(value)
    return where, params


def _user_filters(filters: dict[str, Any]) -> tuple[list[str], list[Any]]:
    where, params = _build_filters(
        filters,
        {
            "department": "department",
            "job_role": "job_role",
            "status": "status",
        },
    )
    search = filters.get("search")
    if search:
        where.append(
            "(lower(username) LIKE %s OR lower(full_name) LIKE %s OR lower(email) LIKE %s)"
        )
        term = f"%{search.lower()}%"
        params.extend([term, term, term])
    return where, params


def _device_filters(filters: dict[str, Any]) -> tuple[list[str], list[Any]]:
    return _build_filters(
        filters,
        {
            "status": "d.status",
            "os": "d.os",
            "assigned_user_id": "d.assigned_user_id",
        },
    )


def _event_filters(filters: dict[str, Any]) -> tuple[list[str], list[Any]]:
    return _build_filters(
        filters,
        {
            "user_id": "user_id",
            "device_id": "device_id",
            "event_type": "event_type",
        },
    )


def _fetch_all(
    base_sql: str,
    where: list[str],
    params: list[Any],
    order_by: str,
    filters: dict[str, Any],
) -> list[dict[str, Any]]:
    sql = base_sql
    if where:
        sql += " WHERE " + " AND ".join(where)
    sql += f" ORDER BY {order_by} LIMIT %s OFFSET %s"
    params = [*params, filters.get("limit", 50), filters.get("offset", 0)]
    with get_connection() as conn:
        return [_row_to_dict(row) or {} for row in conn.execute(sql, params).fetchall()]


def _count(table: str, where: list[str], params: list[Any]) -> int:
    sql = f"SELECT COUNT(*) AS count FROM {table}"
    if where:
        sql += " WHERE " + " AND ".join(where)
    with get_connection() as conn:
        return int(conn.execute(sql, params).fetchone()["count"])


def _update_by_id(
    table: str, row_id: str, payload: dict[str, Any], *, allowed: set[str]
) -> dict[str, Any] | None:
    updates = {key: value for key, value in payload.items() if key in allowed}
    if not updates:
        return get_user(row_id) if table == "users" else get_device(row_id)
    updates["updated_at"] = utc_now()
    assignments = ", ".join(f"{key} = %s" for key in updates)
    values = [*updates.values(), row_id]
    with get_connection() as conn:
        result = conn.execute(f"UPDATE {table} SET {assignments} WHERE id = %s", values)
        if result.rowcount == 0:
            return None
    return get_user(row_id) if table == "users" else get_device(row_id)


def _row_to_dict(row: dict[str, Any] | None) -> dict[str, Any] | None:
    if row is None:
        return None
    return dict(row)


def _decode_json_fields(row: dict[str, Any]) -> dict[str, Any]:
    for key in (
        "metadata_json",
        "raw_json",
        "risk_factors_json",
        "feature_summary_json",
        "baseline_context_json",
        "raw_payload_json",
        "ingest_metadata_json",
    ):
        if key in row:
            decoded_key = key.removesuffix("_json")
            row[decoded_key] = json.loads(row.pop(key) or "{}")
    return row
