from contextlib import contextmanager

import pytest
from pydantic import ValidationError

from src.models.schemas import RawLogBatchIngest, RawLogIngest
from src.services import database


class FakeCursor:
    def __init__(self, row: dict | None = None, rows: list[dict] | None = None) -> None:
        self._row = row
        self._rows = rows or []

    def fetchone(self) -> dict | None:
        return self._row

    def fetchall(self) -> list[dict]:
        return self._rows


class FakeConnection:
    def __init__(self) -> None:
        self.calls: list[tuple[str, tuple | list | None]] = []

    def execute(self, sql: str, params: tuple | list | None = None) -> FakeCursor:
        self.calls.append((sql, params))
        if "RETURNING *" in sql:
            return FakeCursor(
                {
                    "id": 17,
                    "source_id": "pytest:logon:1",
                    "source_file": "logon.csv",
                    "timestamp": "2010-01-04T08:15:00Z",
                    "user_id": "ACM0001",
                    "device_id": "PC-1001",
                    "event_type": "logon",
                    "action": "Logon",
                    "resource": "PC-1001",
                    "metadata_json": '{"source": "pytest"}',
                    "raw_json": '{"line": 1}',
                    "created_at": "2026-06-13T00:00:00Z",
                }
            )
        if sql.strip().upper().startswith("SELECT"):
            return FakeCursor(None)
        return FakeCursor({"count": 0})


def test_initialize_database_uses_postgresql_schema(monkeypatch) -> None:
    fake_conn = FakeConnection()

    @contextmanager
    def fake_get_connection():
        yield fake_conn

    monkeypatch.setattr(database, "get_connection", fake_get_connection)
    monkeypatch.setattr(database, "hash_password", lambda password: f"hashed:{password}")

    database.initialize_database()

    all_sql = "\n".join(sql for sql, _params in fake_conn.calls)
    assert "GENERATED BY DEFAULT AS IDENTITY" in all_sql
    assert "REFERENCES users(id)" in all_sql
    assert "ON CONFLICT(email) DO NOTHING" in all_sql
    assert "ON CONFLICT(id) DO NOTHING" in all_sql
    assert "CREATE INDEX IF NOT EXISTS idx_event_logs_timestamp" in all_sql
    assert "CHECK (event_type IN (" in all_sql
    assert "ALTER TABLE raw_user_logs ADD CONSTRAINT" in all_sql
    assert "idx_raw_user_logs_collector_type" in all_sql
    assert "UPDATE raw_user_logs SET event_type = 'custom'" in all_sql
    assert "pg_constraint c" in all_sql
    assert "pg_class r" in all_sql
    assert "pg_namespace n" in all_sql
    assert "AUTOINCREMENT" not in all_sql
    assert "PRAGMA" not in all_sql


def test_ingest_event_uses_postgresql_upsert_and_decodes_json(monkeypatch) -> None:
    fake_conn = FakeConnection()

    @contextmanager
    def fake_get_connection():
        yield fake_conn

    monkeypatch.setattr(database, "get_connection", fake_get_connection)

    event = database.ingest_event(
        {
            "source_id": "pytest:logon:1",
            "source_file": "logon.csv",
            "timestamp": "2010-01-04T08:15:00Z",
            "user_id": "ACM0001",
            "device_id": "PC-1001",
            "event_type": "logon",
            "action": "Logon",
            "resource": "PC-1001",
            "metadata": {"source": "pytest"},
            "raw": {"line": 1},
        }
    )

    sql, params = fake_conn.calls[0]
    assert "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)" in sql
    assert "ON CONFLICT(source_id) DO UPDATE SET" in sql
    assert "RETURNING *" in sql
    assert params[0] == "pytest:logon:1"
    assert event["metadata"] == {"source": "pytest"}
    assert event["raw"] == {"line": 1}


def test_postgresql_filters_use_percent_s_placeholders() -> None:
    user_where, user_params = database._user_filters(
        {"department": "Finance", "status": "active", "search": "alice"}
    )
    event_where, event_params = database._event_filters(
        {"user_id": "ACM0001", "event_type": "logon"}
    )

    assert "department = %s" in user_where
    assert "status = %s" in user_where
    assert (
        "(lower(username) LIKE %s OR lower(full_name) LIKE %s OR lower(email) LIKE %s)"
        in user_where
    )
    assert user_params == ["Finance", "active", "%alice%", "%alice%", "%alice%"]
    assert event_where == ["user_id = %s", "event_type = %s"]
    assert event_params == ["ACM0001", "logon"]


class FakeRawLogCursor:
    def __init__(self, row: dict | None = None, rows: list[dict] | None = None) -> None:
        self._row = row
        self._rows = rows or []

    def fetchone(self) -> dict | None:
        return self._row

    def fetchall(self) -> list[dict]:
        return self._rows


class FakeRawLogConnection:
    def __init__(self) -> None:
        self.calls: list[tuple[str, tuple | list | None]] = []

    def execute(self, sql: str, params: tuple | list | None = None) -> FakeRawLogCursor:
        self.calls.append((sql, params))
        if "RETURNING *" in sql:
            return FakeRawLogCursor(
                {
                    "id": 1,
                    "source_id": "agent:PC-1001:logon:2026-06-15T08:15:00Z",
                    "collector_type": "endpoint_agent",
                    "event_type": "logon",
                    "timestamp": "2026-06-15T08:15:00Z",
                    "user_id": "ACM0001",
                    "device_id": "PC-1001",
                    "raw_payload_json": '{"action": "Logon", "username": "acm0001"}',
                    "ingest_metadata_json": '{"agent_version": "0.1.0"}',
                    "normalized_event_id": None,
                    "created_at": "2026-06-15T00:00:00Z",
                }
            )
        return FakeRawLogCursor({"count": 0})


def test_raw_log_schema_validates_required_fields() -> None:
    with pytest.raises(ValidationError):
        RawLogIngest.model_validate({})


def test_raw_log_schema_keeps_arbitrary_raw_payload() -> None:
    log = RawLogIngest(
        source_id="test:1",
        collector_type="endpoint_agent",
        event_type="logon",
        timestamp="2026-06-15T08:15:00Z",
        raw_payload={"action": "Logon", "custom_key": "custom_value", "nested": {"a": 1}},
    )
    assert log.raw_payload["custom_key"] == "custom_value"
    assert log.raw_payload["nested"]["a"] == 1


def test_raw_log_schema_rejects_invalid_event_type() -> None:
    with pytest.raises(ValidationError, match="event_type"):
        RawLogIngest(
            source_id="test:1",
            collector_type="endpoint_agent",
            event_type="lgoon",
            timestamp="2026-06-15T08:15:00Z",
        )


def test_raw_log_schema_rejects_invalid_timestamp() -> None:
    with pytest.raises(ValidationError, match="timestamp"):
        RawLogIngest(
            source_id="test:1",
            collector_type="endpoint_agent",
            event_type="logon",
            timestamp="not-a-date",
        )


def test_raw_log_batch_schema_max_1000_records() -> None:
    records = [
        {
            "source_id": f"test:{i}",
            "collector_type": "agent",
            "event_type": "logon",
            "timestamp": "2026-06-15T08:15:00Z",
        }
        for i in range(1001)
    ]
    with pytest.raises(ValidationError):
        RawLogBatchIngest(records=records)


def test_ingest_raw_log_uses_postgresql_upsert(monkeypatch) -> None:
    fake_conn = FakeRawLogConnection()

    @contextmanager
    def fake_get_connection():
        yield fake_conn

    monkeypatch.setattr(database, "get_connection", fake_get_connection)

    result = database.ingest_raw_log(
        {
            "source_id": "agent:PC-1001:logon:2026-06-15T08:15:00Z",
            "collector_type": "endpoint_agent",
            "event_type": "logon",
            "timestamp": "2026-06-15T08:15:00Z",
            "user_id": "ACM0001",
            "device_id": "PC-1001",
            "raw_payload": {"action": "Logon", "username": "acm0001"},
            "ingest_metadata": {"agent_version": "0.1.0"},
        }
    )

    sql, params = fake_conn.calls[0]
    assert "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)" in sql
    assert "ON CONFLICT(source_id) DO UPDATE SET" in sql
    assert "RETURNING *" in sql
    assert params[0] == "agent:PC-1001:logon:2026-06-15T08:15:00Z"
    assert result["raw_payload"] == {"action": "Logon", "username": "acm0001"}
    assert result["ingest_metadata"] == {"agent_version": "0.1.0"}


def test_raw_log_json_fields_decode() -> None:
    row = {
        "id": 1,
        "source_id": "test:1",
        "collector_type": "endpoint_agent",
        "event_type": "logon",
        "timestamp": "2026-06-15T08:15:00Z",
        "raw_payload_json": '{"action": "Logon"}',
        "ingest_metadata_json": '{"agent_version": "0.1.0"}',
        "created_at": "2026-06-15T00:00:00Z",
    }
    decoded = database._decode_raw_log_fields(row)
    assert decoded["raw_payload"] == {"action": "Logon"}
    assert decoded["ingest_metadata"] == {"agent_version": "0.1.0"}
    assert "raw_payload_json" not in decoded
    assert "ingest_metadata_json" not in decoded


def test_raw_log_filters_use_percent_s_placeholders() -> None:
    where, params = database._raw_log_filters(
        {
            "user_id": "ACM0001",
            "device_id": "PC-1001",
            "event_type": "logon",
            "collector_type": "endpoint_agent",
        }
    )
    assert "user_id = %s" in where
    assert "device_id = %s" in where
    assert "event_type = %s" in where
    assert "collector_type = %s" in where
    assert params == ["ACM0001", "PC-1001", "logon", "endpoint_agent"]


def test_batch_ingest_returns_errors_per_record(monkeypatch) -> None:
    call_count = 0

    class BatchFakeCursor:
        def fetchone(self):
            return None

    class BatchFakeConnection:
        def __init__(self):
            self.calls = []

        def execute(self, sql, params=None):
            self.calls.append((sql, params))
            nonlocal call_count
            if "INSERT INTO raw_user_logs" in sql:
                call_count += 1
                if call_count == 2:
                    raise RuntimeError("Simulated failure")
            return BatchFakeCursor()

    fake_conn = BatchFakeConnection()

    @contextmanager
    def fake_get_connection():
        yield fake_conn

    monkeypatch.setattr(database, "get_connection", fake_get_connection)

    records = [
        {
            "source_id": "test:1",
            "collector_type": "agent",
            "event_type": "logon",
            "timestamp": "2026-01-01T00:00:00Z",
        },
        {
            "source_id": "test:2",
            "collector_type": "agent",
            "event_type": "logon",
            "timestamp": "2026-01-01T00:00:00Z",
        },
        {
            "source_id": "test:3",
            "collector_type": "agent",
            "event_type": "logon",
            "timestamp": "2026-01-01T00:00:00Z",
        },
    ]

    result = database.batch_ingest_raw_logs(records)

    assert result["created_or_updated"] == 2
    assert result["failed"] == 1
    assert len(result["errors"]) == 1
    assert result["errors"][0]["index"] == 1
    assert result["errors"][0]["error"] == "failed_to_ingest_record"


def test_migration_skips_alter_when_constraint_exists(monkeypatch) -> None:
    calls: list[str] = []

    class ConstraintExistsCursor:
        def fetchone(self):
            return {"1": 1}

        def fetchall(self):
            return []

    class ConstraintExistsConnection:
        def execute(self, sql, params=None):
            calls.append(sql)
            return ConstraintExistsCursor()

    fake_conn = ConstraintExistsConnection()

    @contextmanager
    def fake_get_connection():
        yield fake_conn

    monkeypatch.setattr(database, "get_connection", fake_get_connection)
    monkeypatch.setattr(database, "hash_password", lambda password: f"hashed:{password}")

    database.initialize_database()

    all_sql = "\n".join(calls)
    assert "ALTER TABLE raw_user_logs" not in all_sql
    assert "UPDATE raw_user_logs SET event_type" not in all_sql


def test_migration_auto_fixes_invalid_event_type(monkeypatch) -> None:
    update_calls: list[tuple[str, tuple | list | None]] = []

    class AutoFixCursor:
        def __init__(self, constraint_exists=False):
            self._constraint_exists = constraint_exists

        def fetchone(self):
            if self._constraint_exists:
                return {"1": 1}
            return None

        def fetchall(self):
            return []

    class AutoFixConnection:
        def __init__(self):
            self.constraint_exists = False

        def execute(self, sql, params=None):
            if "UPDATE raw_user_logs SET event_type" in sql:
                update_calls.append((sql, params))
            if "ALTER TABLE" in sql:
                self.constraint_exists = True
            return AutoFixCursor(constraint_exists=self.constraint_exists)

    fake_conn = AutoFixConnection()

    @contextmanager
    def fake_get_connection():
        yield fake_conn

    monkeypatch.setattr(database, "get_connection", fake_get_connection)
    monkeypatch.setattr(database, "hash_password", lambda password: f"hashed:{password}")

    database.initialize_database()

    assert len(update_calls) == 1
    sql, params = update_calls[0]
    assert "SET event_type = 'custom'" in sql
    assert "NOT IN" in sql
    assert params == list(database._RAW_LOG_EVENT_TYPES)


def test_batch_ingest_release_savepoint_on_error(monkeypatch) -> None:
    call_count = 0

    class BatchFakeCursor:
        def fetchone(self):
            return None

    class BatchFakeConnection:
        def __init__(self):
            self.calls = []

        def execute(self, sql, params=None):
            self.calls.append(sql)
            nonlocal call_count
            if "INSERT INTO raw_user_logs" in sql:
                call_count += 1
                if call_count == 2:
                    raise RuntimeError("Simulated failure")
            return BatchFakeCursor()

    fake_conn = BatchFakeConnection()

    @contextmanager
    def fake_get_connection():
        yield fake_conn

    monkeypatch.setattr(database, "get_connection", fake_get_connection)

    records = [
        {
            "source_id": "test:1",
            "collector_type": "agent",
            "event_type": "logon",
            "timestamp": "2026-01-01T00:00:00Z",
        },
        {
            "source_id": "test:2",
            "collector_type": "agent",
            "event_type": "logon",
            "timestamp": "2026-01-01T00:00:00Z",
        },
        {
            "source_id": "test:3",
            "collector_type": "agent",
            "event_type": "logon",
            "timestamp": "2026-01-01T00:00:00Z",
        },
    ]

    result = database.batch_ingest_raw_logs(records)

    assert result["created_or_updated"] == 2
    assert result["failed"] == 1

    rollback_count = sum(1 for sql in fake_conn.calls if "ROLLBACK TO SAVEPOINT" in sql)
    release_after_rollback = sum(
        1
        for i, sql in enumerate(fake_conn.calls)
        if "RELEASE SAVEPOINT" in sql
        and i > 0
        and "ROLLBACK TO SAVEPOINT" in fake_conn.calls[i - 1]
    )
    release_success = sum(1 for sql in fake_conn.calls if "RELEASE SAVEPOINT" in sql)

    assert rollback_count == 1
    assert release_after_rollback == 1
    assert release_success >= 2
