from contextlib import contextmanager

from src.services import database


class FakeCursor:
    def __init__(self, row: dict | None = None, rows: list[dict] | None = None) -> None:
        self._row = row
        self._rows = rows or []

    def fetchone(self) -> dict | None:
        return self._row

    def fetchall(self) -> list[dict]:
        return self._rows


class FakeConnection:
    def __init__(self) -> None:
        self.calls: list[tuple[str, tuple | list | None]] = []

    def execute(self, sql: str, params: tuple | list | None = None) -> FakeCursor:
        self.calls.append((sql, params))
        if "RETURNING *" in sql:
            return FakeCursor(
                {
                    "id": 17,
                    "source_id": "pytest:logon:1",
                    "source_file": "logon.csv",
                    "timestamp": "2010-01-04T08:15:00Z",
                    "user_id": "ACM0001",
                    "device_id": "PC-1001",
                    "event_type": "logon",
                    "action": "Logon",
                    "resource": "PC-1001",
                    "metadata_json": '{"source": "pytest"}',
                    "raw_json": '{"line": 1}',
                    "created_at": "2026-06-13T00:00:00Z",
                }
            )
        return FakeCursor({"count": 0})


def test_initialize_database_uses_postgresql_schema(monkeypatch) -> None:
    fake_conn = FakeConnection()

    @contextmanager
    def fake_get_connection():
        yield fake_conn

    monkeypatch.setattr(database, "get_connection", fake_get_connection)
    monkeypatch.setattr(database, "hash_password", lambda password: f"hashed:{password}")

    database.initialize_database()

    all_sql = "\n".join(sql for sql, _params in fake_conn.calls)
    assert "GENERATED BY DEFAULT AS IDENTITY" in all_sql
    assert "REFERENCES users(id)" in all_sql
    assert "ON CONFLICT(email) DO NOTHING" in all_sql
    assert "ON CONFLICT(id) DO NOTHING" in all_sql
    assert "CREATE INDEX IF NOT EXISTS idx_event_logs_timestamp" in all_sql
    assert "AUTOINCREMENT" not in all_sql
    assert "PRAGMA" not in all_sql


def test_ingest_event_uses_postgresql_upsert_and_decodes_json(monkeypatch) -> None:
    fake_conn = FakeConnection()

    @contextmanager
    def fake_get_connection():
        yield fake_conn

    monkeypatch.setattr(database, "get_connection", fake_get_connection)

    event = database.ingest_event(
        {
            "source_id": "pytest:logon:1",
            "source_file": "logon.csv",
            "timestamp": "2010-01-04T08:15:00Z",
            "user_id": "ACM0001",
            "device_id": "PC-1001",
            "event_type": "logon",
            "action": "Logon",
            "resource": "PC-1001",
            "metadata": {"source": "pytest"},
            "raw": {"line": 1},
        }
    )

    sql, params = fake_conn.calls[0]
    assert "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)" in sql
    assert "ON CONFLICT(source_id) DO UPDATE SET" in sql
    assert "RETURNING *" in sql
    assert params[0] == "pytest:logon:1"
    assert event["metadata"] == {"source": "pytest"}
    assert event["raw"] == {"line": 1}


def test_postgresql_filters_use_percent_s_placeholders() -> None:
    user_where, user_params = database._user_filters(
        {"department": "Finance", "status": "active", "search": "alice"}
    )
    event_where, event_params = database._event_filters({"user_id": "ACM0001", "event_type": "logon"})

    assert "department = %s" in user_where
    assert "status = %s" in user_where
    assert "(lower(username) LIKE %s OR lower(full_name) LIKE %s OR lower(email) LIKE %s)" in user_where
    assert user_params == ["Finance", "active", "%alice%", "%alice%", "%alice%"]
    assert event_where == ["user_id = %s", "event_type = %s"]
    assert event_params == ["ACM0001", "logon"]
